site_name: Tutorial para ROS 2 Scara

copyright: >
  Derechos de autor &copy; 2023 
  <a href="https://github.com/Ph0n1x0">Luis Miguel Loaiza</a>, 
  <a href="https://github.com/David-8a">David Ochoa</a>, 
  <a href="https://github.com/davinsony">Davinson Casta√±o-Cano</a>.

theme:
  name: readthedocs
  locale: es

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js